name: CanonicalPcPres
version: "1.0"
license: "GPL-2.0-or-later"
date: 2026-07-11
description: |
    Canonical Presentations of Finite Solvable Groups

authors:
    - name: Santiago Barrera Acevedo
      url: https://scholars.latrobe.edu.au/s2barreraace
    - name: Heiko Dietrich
      url: http://users.monash.edu.au/~heikod/
    - name: Max Horn
      url: https://www.quendi.de/math

maintainers:
    - name: Santiago Barrera Acevedo
      url: https://scholars.latrobe.edu.au/s2barreraace
    - name: Heiko Dietrich
      url: http://users.monash.edu.au/~heikod/
    - name: Max Horn
      url: https://www.quendi.de/math

GAP: ">= 4.13"

needed-pkgs:
    - name: "anupq"
      version: ">= 3.3.0"
      url: "https://gap-packages.github.io/anupq/"
    - name: "orb"
      version: ">= 4.9"
      url: "https://gap-packages.github.io/orb"
    - name: "images"
      version: ">= 1.3"
      url: "https://gap-packages.github.io/images/"

www: https://gap-packages.github.io/CanonicalPcPres/
readme: README.md
packageinfo: https://gap-packages.github.io/CanonicalPcPres/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/CanonicalPcPres/releases/download/v1.0/CanonicalPcPres-1.0.tar.gz

abstract: |
    The <span class="pkgname">CanonicalPcPres</span> package computes canonical polycyclic presentations of finite solvable groups, together with explicit isomorphisms from the input groups to their canonical presentations.

doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    canonical presentations, solvable groups, pc groups, group isomorphisms.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>ADH26</span>]   <b class='BibAuthor'>Barrera Acevedo, S., Dietrich, H. and Horn, M.</b>,
     <i class='BibTitle'>CanonicalPcPres, Canonical Presentations of Finite Solvable Groups,
             Version 1.0</i>
     (<span class='BibYear'>2026</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/CanonicalPcPres/">https://gap-packages.github.io/CanonicalPcPres/</a></span>.
    </p>
    

bibtex: |
    @misc{ CanonicalPcPres,
      author =           {{Barrera Acevedo}, S. and Dietrich, H. and Horn, M.},
      title =            {{CanonicalPcPres},  {Canonical Presentations of Finite
                          Solvable Groups}, {V}ersion 1.0},
      month =            {Jul},
      year =             {2026},
      note =             {GAP package},
      howpublished =     {\href
                          {https://gap-packages.github.io/CanonicalPcPres/}
                          {\texttt{https://gap\texttt{\symbol{45}}packages.github.io/}\discretionary
                          {}{}{}\texttt{CanonicalPcPres/}}},
      keywords =         {canonical  presentations;  solvable groups; pc groups;
                          group isomorphisms},
      printedkey =       {ADH26}
    }

