# CanonicalPcPres, chapter 1
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("canonicalpcpres01.tst");

# doc/_Chapter_Overview.xml:61-73
gap> LoadPackage("CanonicalPcPres");;
gap> G := Group([ (9,10)(11,12)(13,14), (1,2), (3,4), (8,9,11,13,14,12,10) ]);;
gap> iso := IsomorphismCanonicalPcGroup(G);
[ (9,10)(11,12)(13,14), (1,2), (3,4), (8,9,11,13,14,12,10) ] -> 
[ f3, f2, f1, f4^5 ]
gap> Source(iso) = G;
true
gap> IsBijective(iso);
true
gap> Range(iso) = CanonicalPcGroup(G);
true

# doc/_Chapter_Overview.xml:92-120
gap> G := Group([ (9,10)(11,12)(13,14), (1,2), (3,4), (8,9,11,13,14,12,10) ]);;
gap> H := SmallGroup(56, 12);;
gap> CanonicalPcGroup(G) = CanonicalPcGroup(H);
false
gap> Size(H) = Size(G);
true
gap> CodePcGroup(CanonicalPcGroup(G));
3649541
gap> CodePcGroup(CanonicalPcGroup(H));
3649541
gap> PrintPcPresentation(CanonicalPcGroup(G),true);
g1^2 = id
g2^2 = id
g3^2 = id
g4^7 = id
[g4,g3] = g4^5
true
gap> PrintPcPresentation(CanonicalPcGroup(H),true);
g1^2 = id
g2^2 = id
g3^2 = id
g4^7 = id
[g4,g3] = g4^5
true
gap> L := List([1..10], i->PcGroupCode(RandomSpecialPcgsCoded(H),Size(H)));;
gap> ForAll(L, U -> CodePcGroup(CanonicalPcGroup(U)) = 3649541);
true

#
gap> STOP_TEST("canonicalpcpres01.tst", 1);
