# CanonicalPcPres, chapter 2
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("canonicalpcpres02.tst");

# doc/_Chapter_Reference.xml:20-26
gap> G := SmallGroup(36, 9);;
gap> H := CanonicalPcGroup(G);
<pc group of size 36 with 4 generators>
gap> Size(H);
36

# doc/_Chapter_Reference.xml:48-53
gap> G := SmallGroup(24, 12);;
gap> iso := IsomorphismCanonicalPcGroup(G);;
gap> [ Source(iso) = G, Size(Range(iso)) ];
[ true, 24 ]

#
gap> STOP_TEST("canonicalpcpres02.tst", 1);
